"""empty message

Revision ID: 8f5ff3bb40f7
Revises: 0679e7d00daf
Create Date: 2025-05-29 17:42:35.185415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5ff3bb40f7'
down_revision = '0679e7d00daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eyes_color', sa.String(), nullable=False))
        batch_op.drop_column('eyers_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eyers_color', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('eyes_color')

    # ### end Alembic commands ###
